### ISSUE TITLE
Unable to see UI

### ISSUE THREAD

**Issue by shahishasank** [socialAPIS/YoutubeDownloader-GUI-PHP#2]
![image](https://user-images.githubusercontent.com/32937688/83939692-8567f000-a7fc-11ea-9253-ff8484508f14.png)
PHP v7.2
Using xampp server
Issue: Unable to see user interface for input. Only navigation bar is viewable
This is how I'm running this application, http://localhost:8080/ytd3/src/FrontEnd/index.html
Please correct me if I'm wrong.

**Comment by socialAPIS** [comment]
You didn't do it the right way.
To folder FrontEnd shouldn't be accesses directly, we have a controller, he do it for us.
Second im using routes in the JS, that means /index.html is not a valid route.

Just extract the release archive in htdocs, go to XAMPP panel and start it from there.
Go then to https://localhost/ and it should work.

**Comment by shahishasank** [comment]
When I run it directly, it gives me Object not found error.
I have installed composer already.

**Comment by socialAPIS** [comment]
I fixed it,
Before running the command `composer install`, type first `composer clearcache`
Here is a video [of installation](https://im4.ezgif.com/tmp/ezgif-4-54787d3e8e68.mp4)
These video link should be available for few days i think

**Comment by shahishasank** [comment]
It works only when I put files directly in htdocs, but not working when files are in htdocs/anyFolder/

**Comment by shahishasank** [comment]
also when I insert the link(https://www.youtube.com/watch?v=arj7oStGLkU) and click on download,
error.log file says
`[Mon Jun 08 04:22:28.540934 2020] [php7:warn] [pid 3184:tid 1656] [client ::1:50025] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in C:\\xampp\\htdocs\\vendor\\guzzlehttp\\guzzle\\src\\Handler\\CurlFactory.php on line 67, referer: http://localhost:8080/
[Mon Jun 08 04:22:28.882414 2020] [php7:error] [pid 3184:tid 1656] [client ::1:50025] PHP Fatal error:  Uncaught Laminas\\HttpHandlerRunner\\Exception\\EmitterException: Output has been emitted previously; cannot emit response in C:\\xampp\\htdocs\\vendor\\laminas\\laminas-httphandlerrunner\\src\\Exception\\EmitterException.php:24\nStack trace:\n#0 C:\\xampp\\htdocs\\vendor\\laminas\\laminas-httphandlerrunner\\src\\Emitter\\SapiEmitterTrait.php(40): Laminas\\HttpHandlerRunner\\Exception\\EmitterException::forOutputSent()\n#1 C:\\xampp\\htdocs\\vendor\\laminas\\laminas-httphandlerrunner\\src\\Emitter\\SapiEmitter.php(27): Laminas\\HttpHandlerRunner\\Emitter\\SapiEmitter->assertNoPreviousOutput()\n#2 C:\\xampp\\htdocs\\src\\public\\index.php(19): Laminas\\HttpHandlerRunner\\Emitter\\SapiEmitter->emit(Object(GuzzleHttp\\Psr7\\Response))\n#3 {main}\n  thrown in C:\\xampp\\htdocs\\vendor\\laminas\\laminas-httphandlerrunner\\src\\Exception\\EmitterException.php on line 24, referer: http://localhost:8080/
`

And

![image](https://user-images.githubusercontent.com/32937688/83981941-18f60980-a940-11ea-8bff-3991ed51bbcb.png)

**Comment by shahishasank** [comment]
[Here](https://drive.google.com/file/d/1EPddnUYGKSxK4mVLtyMWZQr1Fp1hcdIH/view?usp=sharing) is the video of my installation

**Comment by socialAPIS** [comment]
I Will try it today with your link and ill update it. srry..
